/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) throws Exception {
        MyArrayList<String> myArrayList = new MyArrayList<>();
        for (int i = 0; i < 7; i++) {
            myArrayList.add(String.valueOf(i));
        }
        System.out.println(myArrayList);
        myArrayList.add(3, "Element");
        System.out.println(myArrayList);

        myArrayList.remove(2);
        System.out.println(myArrayList);
    }
}

